gcpCreds: "creds/content-creator-424800-77c44a16a43f.json"
redditCreds: "creds/reddit.json"
fontDir: "/usr/share/fonts"
subreddits:
- name: "AmITheAsshole"
  postMinLength: 1000
  usedIDFile: "data/AmITheAsshole.txt"
  instagramCreds: "creds/AmITheAsshole/instagram.json"
  tiktokCreds: "creds/AmITheAsshole/tiktok.json"
  youtubeCreds: "creds/AmITheAsshole/youtube.json"
  font: "ComicSansMS"
  voice: "en-US-Standard-H"